### ISSUE TITLE
Boa

### ISSUE THREAD

**Issue by Guilherm3Rodrigues** [cayo-rodrigues/nff#31]
O programa ajuda a ganhar tempo principalmente quando se trata de fazer varias notas fiscais, posso realizar outras tarefas enquanto ele roda.

A nota versao corrige o problema de valores de produtos quebrados, que antes nao era aceito o que ajuda muito, mas ainda temos o problema de nao aceitar pessoas sem inscrições estaduais, como orgãos do governo, prefeituras etc. Se adicionar isso, acredito que não terá mais nada há melhorar na parte de FAZER notas fiscais.

E caso a pessoa nao saiba o numero do NCM , poderia haver uma opção de deixar em branco e utilizar o sistema de busca do proprio site , ou quando deixar em branco automaticamente colocar o numero "94019900" que é uma numeração generica para referir qualquer coisa.

No mais, esta me ajudando bastante o programa

**Comment by cayo-rodrigues** [comment]
PR com a solução -> https://github.com/cayo-rodrigues/nff/pull/32

O que mudou / foi adicionado:

- Suporte para Linux/Mac
- Suporte para destinatários sem inscrição estadual (nesse caso é necessário preencher as informações de endereço no excel)
- Janela do navegador continua aberta após execução do programa
- Maior eficiência na busca em inputs de listas ordenadas
- O campo `"ncm"` agora não é obrigatório, e se deixado em branco, é usado `94019900` como valor padrão
- Novo campo opcional `"informações complementares"` na aba de Nota Fiscal
