### ISSUE TITLE
Features necessarias para um funcionamento geral

### ISSUE THREAD

**Issue by Guilherm3Rodrigues** [cayo-rodrigues/nff#59]
Vou deixar em ordem de necessidade as fetuares que mais são necessarias para atender melhor as pessoas e o projeto atingir da melhor maneira seu objetivo que é de facilitar e agilizar a emissão e cancelamento de notas, e uma sugestão para facilitar a visualização das metricas

**1. Inclusão de opção isenção de IE** (Uma checkbox resolve, reforçar que os dados de rua, bairro, cep são OBRIGATORIOS quando a isenção esta marcada) , e quando marcada selecionar a opção de destinatario isento de IE no campo de dados do remetente, notas fiscais para escolas e prefeitura serão as mais beneficiadas desta feature

**2. Multiplos IEs para produtores.** (Atualmente se um produtor tem mais de uma IE e a venda esta ocorrendo de uma IE secundaria e não a principal que é usada para login, não é possivel fazer a nota pelo programa, quando houver mais de uma IE cadastrada no produtor seja do remetente ou destinatario, haver um <option> com as opções de IE disponiveis e seu respectivo nome, cada IE representa uma fazenda/sitio, poder dar um nickname para eles facilita o processo e torna desnecessario mostrar a numeração na hora de emitir a nota, apenas na aba entidades mostraria para confirmar se esta tudo certo)

**3. Descrição dos CFOPs de venda** , uma descrição facilita principalmente para situações atipicas que fogem do cotidiano, para evitar ter que entrar no site e ler qual CFOP mais se enquadra na situação, a descrição poderia vir junto com a numeração, já encaminho ela

5101 venda de produção do estabelecimento

5102 venda de mercadoria adquirida ou recebida de terceiros, ou qualquer venda de mercadoria efetuada pelo MEI com exceção das saidas classificadas nos codigos 5501, 5502, 5504 e 5505

5103 venda de produção do estabelecimento, efetuada fora do estabelecimento

5105 venda de produçãodo estabelecimento que não deva por transitar

5111 venda de produção do estabelecimento remetida anteriormente em consignação industrial

5113 venda de produção do estabelecimento remetida anteriormente em consignação mercantil

5116 venda de produção do estabelecimento originada de encomenda para entrega

5118 venda de produção do estabelecimento entregue ao destinario por conta e ordem do adquirente originario, em venda ordem

5122 venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente

5159 fornecimento de produção do estabelecimento de ato cooperativo

5160 fornecimento de mercadoria adquirida ou recebida de terceiros de ato cooperativo

5401 venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributaria, na condição de contribuinte substituto

5402 venda de produção do estabelecimento de produto sujeito ao regime de substituição tributaria, em operação entre operação entre contribuintes substitutos do mesmo produto

5551 venda de bem do ativo imobilizado

4. **Aproveita para informar que os CFOPs de REMESSA estão errados, a seguir os corretos com as descrições**

5131: Remessa de produção do estabelecimento, com previsão de posterior ajuste ou fixação de preço, de ato cooperativo

5132: Fixação de preço de produção do estabelecimento, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço de ato cooperativo

5414: Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária

5415: Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária

5451: Remessa de animal e de insumo para estabelecimento produtor

5452	Remessa de insumo - Sistema de Integração e Parceria Rural

5501	Remessa de produção do estabelecimento, com fim específico de exportação

5554	Remessa de bem do ativo imobilizado para uso fora do estabelecimento

5901	Remessa para industrialização por encomenda

5904	Remessa para venda fora do estabelecimento, ou qualquer remessa efetuada pelo MEI com exceção das classificadas nos 
códigos 5.502 e 5.505.

5905	Remessa para depósito fechado ou armazém geral

5908	Remessa de bem por conta de contrato de comodato

5910	Remessa em bonificação, doação ou brinde

5911	Remessa de amostra grátis

5912	Remessa de mercadoria ou bem para demonstração

5914	Remessa de mercadoria ou bem para exposição ou feira

5915	Remessa de mercadoria ou bem para conserto ou reparo

5917	Remessa de mercadoria em consignação mercantil ou industrial

5920	Remessa de vasilhame ou sacaria

5923	Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem

5924	Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento 
do adquirente

5934	Remessa simbólica de mercadoria depositada em armazém geral ou depósito fechado

**Sem essa mudança nas notas de remessa, apesar da opção existir é impossivel no momento emitir-las**

**5. Acrescimo do link** https://www2.fazenda.mg.gov.br/sol/ctrl/SOL/NFAE/CONSULTA_006?ITEM=0&ACAO=VISUALIZAR , para pesquisa de NCM de produtos, no caso de esquecimento, de um produto pouco utilizado, ou um produto nunca feito pelo usuario.

**6. Sobre metricas: Retorno de IE do remetente, e verificação das IEs nas entidades para visualização se alguma das notas analisadas vieram ou não delas**,  se sim, voltar o nome registrado nas entidades, se não, voltar apenas o numero do IE

**7. Botão de cancelar com verificação de confirmação do usuario no historico das proprias notas emitidas, ao lado do "baixar", "usar como modelo", ou "visualizar"**, quando necessario cancelar multiplas notas fiscais, facilita este metodo do que ir até a aba de "cancelar notas fiscais" e digitar o numero dela, ainda vai ser util essa aba pra notas emitidas fora do NFF ou que por algum motivo esta de dificil visualização na aba "emitir notas"

No mais, o que o programa já esta realizando no momento é extremamente competente, rapido e eficaz, de facil entendimento, todas essas sugestões são para melhor atender um maior numero de usuarios

**Comment by Guilherm3Rodrigues** [comment]
Problemas atuais após a implementação das IEs adicionais para remetentes:

1. Metricas parou de funcionar normalmente, funciona para um ou outro, mas para a maioria não funciona, não é possivel identificar se tem alguma relação com as ultimas mudanças

2. CPFs cadastradas com . (ponto) e - (traço) pararam de funcionar ao requerer notas fiscais

3. Cadastro de novas entidades EXTREMAMENTE lento, após requerer o cadastro de uma nova entidade ou atualizar alguma existente demora em torno de 30 mins ou mais para aparecer na lista de entidades as mudanças, inclusive facilmente vc repete o processo achando que fez algo errado e depois aparece varias entidades iguais pq vc fez o requerimento mais de uma vez

**Comment by Guilherm3Rodrigues** [comment]
Obs: "Inclusão de opção isenção de IE" , item um da issue já é possivel do modo que o programa é, erro meu não ter notado isso antes

**Comment by cayo-rodrigues** [comment]
> 1. De fato isso já é possível, dadas as regras de negócio do formulário de registro de entidade ✅
> 2. Parcialmente resolvido. É possível cadastrar e usar multiplos IES em entidades, porém apenas para remetentes. Destinatários ainda precisam dessa opção no formulário de emissão de nota fiscal ⚠️
> 3. Descrição de CFOPs pendente 💬
> 4. Diferenciar CFOPs de venda e de remessa ainda pendente 💬
> 5. Acrescentar link para pesquisa de NCM de produtos, ok ✅
> 6. Melhorar descrição dos registros individuais das métricas, ainda pendente 💬
> 7. Botão para cancelar NFA diretamente no card das notas emitidas, ok ✅
> 
> @Guilherm3Rodrigues

2. Totalmente resolvido. É possível usar multiplos IEs tanto em remetentes quanto em destinatários no momento de emitir notas fiscais ✅ 
3. Formulário de emissão de NF agora possui descrição de cada CFOP ✅ 
4. Campo de CFOP no formulário de emissão de NF mostra diferentes opções, de acordo com o tipo de operação escolhido, seja venda ou remessa ✅

**Comment by cayo-rodrigues** [comment]
> > 1. De fato isso já é possível, dadas as regras de negócio do formulário de registro de entidade ✅
> > 2. Parcialmente resolvido. É possível cadastrar e usar multiplos IES em entidades, porém apenas para remetentes. Destinatários ainda precisam dessa opção no formulário de emissão de nota fiscal ⚠️
> > 3. Descrição de CFOPs pendente 💬
> > 4. Diferenciar CFOPs de venda e de remessa ainda pendente 💬
> > 5. Acrescentar link para pesquisa de NCM de produtos, ok ✅
> > 6. Melhorar descrição dos registros individuais das métricas, ainda pendente 💬
> > 7. Botão para cancelar NFA diretamente no card das notas emitidas, ok ✅
> > 
> > @Guilherm3Rodrigues
> 
> 2. Totalmente resolvido. É possível usar multiplos IEs tanto em remetentes quanto em destinatários no momento de emitir notas fiscais ✅
> 3. Formulário de emissão de NF agora possui descrição de cada CFOP ✅
> 4. Campo de CFOP no formulário de emissão de NF mostra diferentes opções, de acordo com o tipo de operação escolhido, seja venda ou remessa ✅

6. Melhorar descrição dos registros individuais das métricas, OK! ✅ 

![image](https://github.com/user-attachments/assets/c36473f7-4578-4524-b1d4-2ab57110579d)

Pode melhorar o visual? Sim, mas a carne com batatas já está pronta.

---

### Considerações

Talvez fosse interessante, nos casos onde a entidade não é encontrada na nossa base de dados, haver um link para poder consultar o IE naquele site do governo que infelizmente faz verificação de "eu não sou um robô".

@Guilherm3Rodrigues
