### ISSUE TITLE
Erros no aplicativo

### ISSUE THREAD

**Issue by Guilherm3Rodrigues** [cayo-rodrigues/nff#61]
Problemas atuais após a implementação das IEs adicionais para remetentes:

 -   Metricas parou de funcionar normalmente, funciona para um ou outro, mas para a maioria não funciona, não é possivel identificar se tem alguma relação com as ultimas mudanças

-    CPFs cadastradas com . (ponto) e - (traço) pararam de funcionar ao requerer notas fiscais

-    Cadastro de novas entidades EXTREMAMENTE lento, após requerer o cadastro de uma nova entidade ou atualizar alguma existente demora em torno de 30 mins ou mais para aparecer na lista de entidades as mudanças, inclusive facilmente vc repete o processo achando que fez algo errado e depois aparece varias entidades iguais pq vc fez o requerimento mais de uma vez

**Comment by cayo-rodrigues** [comment]
> Problemas atuais após a implementação das IEs adicionais para remetentes:
> 
> * Metricas parou de funcionar normalmente, funciona para um ou outro, mas para a maioria não funciona, não é possivel identificar se tem alguma relação com as ultimas mudanças
> * CPFs cadastradas com . (ponto) e - (traço) pararam de funcionar ao requerer notas fiscais
> * Cadastro de novas entidades EXTREMAMENTE lento, após requerer o cadastro de uma nova entidade ou atualizar alguma existente demora em torno de 30 mins ou mais para aparecer na lista de entidades as mudanças, inclusive facilmente vc repete o processo achando que fez algo errado e depois aparece varias entidades iguais pq vc fez o requerimento mais de uma vez

1. Métricas já voltaram a funcionar, era um pequeno problema relacionado ao campo "outras ies". ✅ 
2. Espero que agora funcione kkkj
3. Problemas no genrenciamento de cache, já foram corrigidos. ✅

**Comment by Guilherm3Rodrigues** [comment]
CPFs com . e - continuam atravando o longin de usuarios no SIARE  (⊃  ˃̣̣̥ ᴖ ˂̣̣̥ ⊂)
