### ISSUE TITLE
[Bug]: Metricas fazendo o site cair

### ISSUE THREAD

**Issue by Guilherm3Rodrigues** [cayo-rodrigues/nff#80]
### Contato

pav@piranguinho.mg.gov.br

### Qual o email cadastrado na sua conta do NFF?

guilherme.rodrigues0666@gmail.com

### O que aconteceu?

Por 2x ao tentar fazer metricas de 1 mes inteiro de um produtor o site caiu

### Quando aconteceu?

22/10/2024

### Como reproduzir o erro?

Tentar gerar metricas de qualquer produtor rural, não foram os mesmos meses mas foi o mesmo produtor que gerou o erro

**Comment by cayo-rodrigues** [comment]
Resolvido na PR https://github.com/cayo-rodrigues/nff/pull/83, mais especificamente no commit https://github.com/cayo-rodrigues/nff/pull/83/commits/c2ec3470ddb267565c5893a6e6388c986d4b21d4
